### ISSUE TITLE
Support for XEP-0401 URIs

### ISSUE THREAD

**Issue by ge0rg** [modernxmpp/easy-xmpp-invitation#17]
The landing page currently only allows adding contacts. It should also support:

* `xmpp:USER@DOMAIN?register` for IBR with a supplied account JID
* `xmpp:DOMAIN?register` for IBR on the supplied service domain

**Comment by mwild1** [comment]
This was fixed in #62 via commit https://github.com/modernxmpp/easy-xmpp-invitation/pull/62/commits/c90c0a0fac9bad11694aa2c384e81479322f9786
