### ISSUE TITLE
Adopt a build system

### ISSUE THREAD

**Issue by strugee** [modernxmpp/easy-xmpp-invitation#3]
As I was authoring #2 I was thinking it'd be nice to have a build system. This would let us do things like uglification, compilation from ES6, maintain the HTML in a nicer-looking language like [Pug][1], etc. However I didn't want to introduce a change that big without approval.

Thoughts?

 [1]: https://pugjs.org/

**Comment by ge0rg** [comment]
I'm not a "modern" "web developer", so consider me conservative. I'm okay with using a build system, a templating engine and whatever else might help, under two conditions:

* it doesn't bloat our "binary" (we are at 11KB total payload now! :D )
* it won't disappear in the next two years (seems to be common with web tools)

**Comment by strugee** [comment]
@ge0rg OK, good to know. Most of that weight is probably coming from Bootstrap, which is close to being gone (see #1). A build system will let us do minification, which will further improve download size.

**Comment by ge0rg** [comment]
I suppose that 11KB is already a huge win, compared to "modern" web sites. It doesn't look like we'll get that reduced significantly, so I don't see this argument as the most urgent one.

I've pulled in #2 and I'd like to see #1 handled next, but it's not a blocker for integrating a build system. If you have a specific one to suggest, please do so.

**Comment by strugee** [comment]
I personally like [gulp][1]. It's fast an Unixy.

 [1]: http://gulpjs.com/

**Comment by mwild1** [comment]
I think all the current contributors are "fine" with the current project. A build system increases the complexity required to contribute to and deploy the site. Of course we'll add a build system if we need one in the future, but since this issue was filed the JS ecosystem has cycled through roughly 5 build systems :)

**Comment by strugee** [comment]
Yeah makes sense. Honestly my tastes have changed since I filed this issue and I'd make the same call. The one thing that might be worth doing is minification of `main.js` which might shave off a few KB or two. You could shave off a request/response cycle by concatenating the QR code library too.

But, <30KB is still pretty good. I wouldn't bother.
