### ISSUE TITLE
Windows clients outdated / misleading

### ISSUE THREAD

**Issue by poVoq** [modernxmpp/easy-xmpp-invitation#63]
See: https://github.com/modernxmpp/easy-xmpp-invitation/blob/master/clients_Windows.json

UWXP is abandoned and Gajim is missing. Dino should probably also be added now that they are working on an official Windows build.

I would also suggest adding Movim (via https://join.movim.eu ), as it is probably the client with the easiest onboarding for Windows users.

**Comment by sjehuda** [comment]
> UWXP is abandoned

It is still available and working, and I guess the owner will welcome new maintainers.

> Gajim is missing

Thanks. I forgot about Gajim!

> Dino should probably also be added now that they are working on an official Windows build

Good news!

> I would also suggest adding Movim (via https://join.movim.eu ), as it is probably the client with the easiest onboarding for Windows users.

Good idea.

**Comment by sjehuda** [comment]
Please create a PR.

**Comment by poVoq** [comment]
https://github.com/modernxmpp/easy-xmpp-invitation/pull/68
