### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by sjehuda** [modernxmpp/easy-xmpp-invitation#67]
XMPP software appear to be getting censored and restrained by factors who do not want others to enjoy decentralized communications.

**Please use F-Droid links instead.**

See https://github.com/modernxmpp/easy-xmpp-invitation/pull/51#issuecomment-2044204146

**Comment by mwild1** [comment]
This issue would help with the F-Droid UX: https://gitlab.com/fdroid/fdroidclient/-/issues/1932

However the fact remains that most people do not have F-Droid installed already. We should encourage it, but having to install F-Droid before they can get chatting involves a *lot* of extra steps and will certainly lose users.

Probably the best option is to offer both.

**Comment by licaon-kter** [comment]
> However the fact remains that most people do not have **an XMPP client** installed already. We should encourage it, but having to install **a client** before they can get chatting involves a lot of extra steps and will certainly lose users. 

Yeah, I know, since Whatsapp is already installed... :roll_eyes:

**Comment by mwild1** [comment]
Sure. We have a hard task to convert people. Making them install one app is hard enough. Making them install two apps, download APKs, tap through multiple security warnings, it's a simple (sad) fact that many will give up and stick to WhatsApp, yes :(

**Comment by licaon-kter** [comment]
> Probably the best option is to offer both.

yup

**Comment by ge0rg** [comment]
No, offering both is not the best option. This project is about making onboarding easier for inexperienced users. Users who have F-Droid installed, or are ready and able to install F-Droid, are by definition not part of the target audience of this project.

The only trade-off that I would potentially accept is one that offers f-droid in an intent selection dialog if f-droid is already installed, like the Android-only `market://details?id=<package_name>` uri scheme. Unfortunately, that only works when clicked from an Android device (restricting usability from a desktop, where you can install an Android app to one of your phones through the Play Store web frontend), and it was obsoleted by Google, so I have no idea when it will stop working. Given those two issues, this is also a non-solution.
